refactor gadgettracermanager and add unit tests
kinvolk/inspektor-gadget pull request #213
Opened 2021-07-28 15:11 UTC by alban

GadgetTracerManager is refactored so it's possible to create an instance
that will not do any privileged operations like using BPF maps.

Then, it's possible to add unit tests.

2021-07-29 15:09 UTC, mauriciovasquezbernal requested changes
Very nice change! I think later on we can create more tests that actually check that the eBPF maps are created and populated correctly. 

I have a blocking comment on a conditional that is misplaced, otherwise LGTM!

2021-07-29 15:09 UTC, mauriciovasquezbernal commented on pkg/gadgettracermanager/gadgettracermanager_test.go
> +					&pb.Label{Key: "key2", Value: "value2"},
We can add a third label and it still will match, right? (just to check that the matching algorithm matches a subset of labels)

2021-07-29 15:09 UTC, mauriciovasquezbernal commented on pkg/gadgettracermanager/gadgettracermanager_test.go
> +			description: "Selector without all filters",
Which filter is missing?

2021-07-29 15:09 UTC, mauriciovasquezbernal commented on pkg/gadgettracermanager/gadgettracermanager_test.go
> +	}
Some ideas for more test cases:
- try to add an already existing tracer
- remove a non existing tracer

2021-07-29 15:09 UTC, mauriciovasquezbernal commented on pkg/gadgettracermanager/gadgettracermanager_test.go
> +
Same ideas as above.

2021-07-29 15:14 UTC, alban commented on pkg/gadgettracermanager/gadgettracermanager_test.go
> +			description: "Selector without all filters",
Oops, I meant

```suggestion
			description: "Selector with all filters",
```

2021-07-30 10:49 UTC, alban commented
Fixed. PTAL.

2021-07-30 12:05 UTC, mauriciovasquezbernal approved these changes
LGTM. Thanks for handling all the comments.

2021-07-30 12:14 UTC, merged