dns gadget: refactor
kinvolk/inspektor-gadget pull request #508
Opened 2022-02-15 16:52 UTC by alban

# dns gadget: refactor

During the review of #369, there were changes suggested to the dns gadget. This PR introduces the suggested change, taking example on execsnoop. This will make it easier to write the snisnoop gadget without duplicating too much code.

2022-02-15 21:54 UTC, mauriciovasquezbernal requested changes
Looks good overall. 

Requesting changes because I think you added the `String()` method to the wrong package and the gadget is not working now -> https://github.com/kinvolk/inspektor-gadget/runs/5203974743?check_suite_focus=true#step:6:198

2022-02-15 21:54 UTC, mauriciovasquezbernal commented on pkg/gadgets/dns/gadget.go
> +			t.publishMessage(trace, eventtypes.ERR, key, fmt.Sprintf("failed to detach tracer: %s", err))
detach -> attach

2022-02-16 15:09 UTC, alban commented on pkg/gadgets/dns/gadget.go
> +			t.resolver.PublishEvent(traceName, event.String())
I see... I wanted to avoid duplicating code for every gadget... I updated with an alternative function.

2022-02-16 15:10 UTC, alban commented on pkg/gadgets/dns/gadget.go
> +	)
Done

2022-02-16 16:02 UTC, mauriciovasquezbernal approved these changes
LGTM!

2022-02-16 16:15 UTC, merged