Create makefile to generate BTF files
kinvolk/inspektor-gadget pull request #710
Opened 2022-06-24 18:14 UTC by mauriciovasquezbernal

Remove the tools/btfgen.sh script and replace it by a Makefile as done in https://github.com/iovisor/bcc/pull/3889. The advantage of this change is that we don't need to worry about updating the btfgen.sh script anymore.

2022-06-28 16:45 UTC, mauriciovasquezbernal commented
How did you try to build it? I'm using `make ENABLE_BTFGEN=true gadget-default-container` and seems to work fine on my machine.

2022-06-28 17:10 UTC, mauriciovasquezbernal commented
Could you please describe the exact commands you're using? The following ones work fine to me:

```
$ make ENABLE_BTFGEN=true gadget-default-container
# or 
$ docker build -f gadget-default.Dockerfile --build-arg ENABLE_BTFGEN=true .
```

2022-06-28 22:01 UTC, mauriciovasquezbernal commented
@eiffel-fl I think I found the issue. Could you please check that there are not old .o files on the bpf folders of IG on your machine?

```
$ ls pkg/gadgets/*/tracer/bpf/*.o
```

For some reason make is assuming it need to update those files compiling the .c files using cc, and of course it's failing because cc is not able to compile bpf code.

2022-06-29 10:28 UTC, alban requested changes

2022-06-29 15:08 UTC, alban commented on Makefile.btfgen
> +endif
Shouldn't it be at the top to be checked before the `find` command is executed? It seems to work like this but I don't understand why.

2022-07-01 13:26 UTC, mauriciovasquezbernal commented on Makefile.btfgen
> +	$(Q)touch $@
That's nice. I updated it. Thanks!

2022-07-05 14:35 UTC, alban approved these changes
LGTM

2022-07-05 14:35 UTC, alban commented on Makefile
> +ARCH := $(shell uname -m | sed 's/x86_64/x86/' | sed 's/aarch64/arm64/' | sed 's/ppc64le/powerpc/' | sed 's/mips.*/mips/')
Should it be changeable by users like this?

```suggestion
ARCH ?= $(shell uname -m | sed 's/x86_64/x86/' | sed 's/aarch64/arm64/' | sed 's/ppc64le/powerpc/' | sed 's/mips.*/mips/')
```

2022-07-05 14:35 UTC, alban commented on .dockerignore
> +!Makefile*
Any reason why not calling the file `btfgen.mk`?

2022-07-05 14:35 UTC, alban commented on Makefile.btfgen
> +all: $(MIN_CORE_BTF_FILES)
```suggestion
.PHONY: all
all: $(MIN_CORE_BTF_FILES)
```

2022-07-05 14:35 UTC, alban commented on Makefile.btfgen
> +# TODO (filter by architecture too when implemented)
I think it is fine to fix this TODO in the other PR

2022-07-05 14:35 UTC, alban commented on Makefile
> +ARCH := $(shell uname -m | sed 's/x86_64/x86/' | sed 's/aarch64/arm64/' | sed 's/ppc64le/powerpc/' | sed 's/mips.*/mips/')
I think it is fine to fix this in the other PR

2022-07-05 15:50 UTC, merged

2022-07-14 19:19 UTC, mauriciovasquezbernal commented on Makefile
> +ARCH := $(shell uname -m | sed 's/x86_64/x86/' | sed 's/aarch64/arm64/' | sed 's/ppc64le/powerpc/' | sed 's/mips.*/mips/')
@eiffel-fl I was iterating again on this to see if BTFGen and arm64 are working fine together. It seems to me they are. I can see the generated BTF files for each platform:

```
$ mkdir -p /tmp/foo/arm64
$ docker create --name arm64 ghcr.io/kinvolk/inspektor-gadget:latest@sha256:02ac6b4aa39b55ab189792ff8b3288304a29ff846aa1494f0b158fac899706a0
$ docker export arm64 > /tmp/foo/arm64/file.tar
$ cd /tmp/foo/arm64
$ tar xvf file.tar
$ tree btfs/ | wc -l
469
```

I opened https://github.com/kinvolk/inspektor-gadget/pull/751 to make it more efficient, but besides that I think it's done. 

What were your concerns about `uname -m` in this case?